### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by tuktukvlad** [1rosehip/jplist-es6#13]
Hi

After the last update, pagination does not work (**data-type="page"**).
Prev and Next buttons it's working.
Here you can [see the demo](https://codepen.io/tuktukvlad/pen/djBpLy?editors=1000)

Thanks

**Comment by 1rosehip** [comment]
Thank you for noticing this, it's fixed. It was related to range slide events change, I've reverted it for now.

**Comment by 1rosehip** [comment]
Fixed in v1.1.1
