### ISSUE TITLE
Pagination view all

### ISSUE THREAD

**Issue by flashmaster82** [1rosehip/jplist-es6#15]
On the previous version of the pagination when you filter(view all) or had less items in your list, the buttons was hidden. In the new version they are visible at all time..

**Comment by 1rosehip** [comment]
**jplist-pages-number-...** and **jplist-items-number-...** [dynamic classes are added to the pagination control](https://www.jplist.org/documentation/controls/pagination#pagination-classes). IMHO it will give the most flexibility to the different HTML structures as a developer can use these classes to hide / show pagination in CSS.

The change is done in v.1.1.2
