### ISSUE TITLE
Less default styles / theming support

### ISSUE THREAD

**Issue by onli** [1rosehip/jplist-es6#17]
Hi. Thanks for this work.

The css has some styles that will clash with many site designs, like `font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;` It would be great if the css could be splitted: One providing the core css absolutely necessary for placement etc, and one second css file with the css specific to the design. 

Like with http://github.hubspot.com/vex/ that could result in support for included themes, but more important is that it owuld make it easier to make jplist for the the site design.

**Comment by 1rosehip** [comment]
Hi, 
Thank you for the feedback.
This version of jPList almost doesn't have CSS styles and in most examples uses Bootstrap framework for demo pages. Developer may use any styles / frameworks that needed and any HTML structure. The only exception is custom dropdown control and range slider as it's not possible to implement them without CSS, but even in these cases the styles are minimal and can be changed in any way.

**Comment by onli** [comment]
Hi, thanks for your answer. The examples tricked me by reusing the bootstrap styles, but that is exactly what is wanted. Very nice.

https://github.com/1rosehip/jplist-es6/blob/master/dist/1.1.2/jplist.styles.css does indeed not many styles. The font-family thing I mentioned, and some color assignments. I believe you that those are really necessary for making the dropdown works.

Looks nice so far!
