### ISSUE TITLE
AJAX Request

### ISSUE THREAD

**Issue by bobsonian** [1rosehip/jplist-es6#18]
Is it possible to request data using ajax and json as per previous version

**Comment by 1rosehip** [comment]
After careful consideration I think that jPList library is not intended to handle AJAX / server version as there are better tools for this in the web. IMHO the best way to handle complicated SPA application is using one of the popular libraries like React, Angular or Vue.js. 

The previous jPList version used JS temples to render HTML returned from the server, but this technology is a bit outdated. The better and more efficient way is to use virtual DOM like react does or other modern framework.

**Comment by sbenfares** [comment]
So if we want to use ajax we have to use jpList older version ?

**Comment by sbenfares** [comment]
If you don't want to handle Ajax could you add a sample/documentation for adding Vue.js ?

**Comment by jiremek** [comment]
@mistersam91  I start to add request for get the data by Ajax.
I have an issue with http.send who make a loop of request, so I commented them.
Maybe you can help me to solve this issue, and so you will also find the solution of your request !!!




			jplist.init();
			if(typeof(jpliststate)=='undefined'){
				var jpliststate = new Object();
				var http = new XMLHttpRequest();
				http.onreadystatechange = function() {//Call a function when the state changes.
				    if(http.readyState == 4 && http.status == 200) {
				    	jplist.resetContent(function(){
				    		// Detruire les résultats actuelles
				    		var theOddOnes = document.getElementsByClassName("list-item");
			                for(var i=0; i<theOddOnes.length; i++){ theOddOnes[i].remove(); }
			                // Charger les résultats
			                
				    	});
				    }
				}
			}
			//get a jPList control element
			const element = document.getElementById('jplist-search-run'); 
			
			//listen to the state event
			element.addEventListener('jplist.state', (e) => {
				var temp_e=e.jplistState.options;
				if( !Object.is(temp_e.pathFilterOptions, jpliststate.pathFilterOptions) || 
					!Object.is(temp_e.rangeFilterOptions, jpliststate.rangeFilterOptions) ||
					!Object.is(temp_e.sortOptions, jpliststate.sortOptions) ||
					!Object.is(temp_e.textFilterOptions, jpliststate.textFilterOptions)
				){
					// transfert des propriétés
					jpliststate.pathFilterOptions=temp_e.pathFilterOptions;
					jpliststate.rangeFilterOptions=temp_e.rangeFilterOptions;
					jpliststate.sortOptions=temp_e.sortOptions;
					jpliststate.textFilterOptions=temp_e.textFilterOptions;
					delete temp_e.paginationOptions;
					if(typeof(http)!='undefined'){
						http.abort();
					}
					var url = '~~fixe~~site_url~~/ac_getdata?action=ranalyze_search_json';
					http.open('POST', url, true);
					
					//Send the proper header information along with the request
					http.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
					console.log('run');
					/* http.send(JSON.stringify(jpliststate));*/
				}
				else{
					console.log((jpliststate.textFilterOptions));
					console.log((temp_e.textFilterOptions));
					console.log(Object.is(temp_e.textFilterOptions, jpliststate.textFilterOptions));
				}
			}, false);

**Comment by jiremek** [comment]
look like jPlist and standard XMLHTTPRequest object have bad interactions.
I now use jQuery and it work:
`jplist.init();
			if(typeof(jpliststate)=='undefined'){
				var jpliststate = new Object();
				var xhr = new Object();
				var is_xhr=false;
			}

			function jplist_ajax_result(){//Call a function when the state changes.
			    if(xhr.readyState == XMLHttpRequest.DONE && xhr.status == 200){
			    	jplist.resetContent(function(){
			    		// Detruire les résultats actuelles
			    		let theOddOnes = document.getElementsByClassName("jplist-item");
		                for(let i=0; i<theOddOnes.length; i++){ theOddOnes[i].remove(); }
		                // Charger les résultats
		                
			    	});
			    }
			    else{
			    	console.log(xhr);
			    }
			    is_xhr=false;
			}
			
			function jplist_ajax(url, data){
				var xhr = $.ajax({
				    type: "POST",
				    url: url,
				    data: data,
				    success: jplist_ajax_result
				});
				var is_xhr=true;
			}
			
			//get a jPList control element
			const element = document.getElementById('jplist-search-run'); /*jplist-control-area');*/
			/*const element = document.getElementById('jplist-search-button');*/
			
			//listen to the state event
			element.addEventListener('jplist.state', (e) => {
				var temp_e=e.jplistState.options;
				if( !Object.is(temp_e.pathFilterOptions, jpliststate.pathFilterOptions) || 
					!Object.is(temp_e.rangeFilterOptions, jpliststate.rangeFilterOptions) ||
					!Object.is(temp_e.sortOptions, jpliststate.sortOptions) ||
					!Object.is(temp_e.textFilterOptions, jpliststate.textFilterOptions)
				){
					// transfert des propriétés
					jpliststate.pathFilterOptions=temp_e.pathFilterOptions;
					jpliststate.rangeFilterOptions=temp_e.rangeFilterOptions;
					jpliststate.sortOptions=temp_e.sortOptions;
					jpliststate.textFilterOptions=temp_e.textFilterOptions;
					delete temp_e.paginationOptions;
					if(typeof(xhr)!='undefined' && is_xhr){
						xhr.abort();
						is_xhr=false;
					}
					var url = '~~fixe~~site_url~~/ac_getdata?action=ranalyze_search_json';

					jplist_ajax(url, JSON.stringify(jpliststate));
				}
				else{
					console.log((jpliststate.textFilterOptions));
					console.log((temp_e.textFilterOptions));
					console.log(Object.is(temp_e.textFilterOptions, jpliststate.textFilterOptions));
				}
			}, false);`

**Comment by jiremek** [comment]
I found the solution:

			jplist.init();
			
			
			if(typeof(jpliststate)=='undefined'){
				jpliststate = new Object();
				http = new XMLHttpRequest();
				http.onreadystatechange = function() {//Call a function when the state changes.
				    if(http.readyState == 4 && http.status == 200) {
				    	jplist.resetContent(function(){
				    		// Detruire les résultats actuelles
				    		var theOddOnes = document.getElementsByClassName("list-item");
			                for(var i=0; i<theOddOnes.length; i++){ theOddOnes[i].remove(); }
			                // Charger les résultats
			                
				    	});
				    }
				}
			}
			
			//get a jPList control element
			const element = document.getElementById('jplist-search-run');
			
			//listen to the state event
			element.addEventListener('jplist.state', (e) => {
				delete e.jplistState.options.paginationOptions; // dont run request on page change
				temp_e=JSON.stringify(e.jplistState.options);
				if( temp_e!==jpliststate){
					// transfert des propriétés
					jpliststate=temp_e;
					
					if(typeof(http)!="undefined"){
						http.abort();
					}
					var url = '~~fixe~~site_url~~/ac_getdata?action=ranalyze_search_json';
					http.open('POST', url, true);
					
					//Send the proper header information along with the request
					http.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
					http.send(jpliststate);
				}
			}, false);

**Comment by sbenfares** [comment]
Thanks @jiremek !

PS : Are u french ? Si c'est le cas je t'envoie un MP ;)

**Comment by jiremek** [comment]
et oui:)

**Comment by sbenfares** [comment]
@jiremek je n'ai pas réussi à trouver ton adresse mail, peux-tu me contacter sur sbenfares@gmail.com ?

Merci

**Comment by jiremek** [comment]
@mistersam91 je ne sais pas si tu as bien reçu mon mail.
evidement, si ce que nous faisons est bénéfique au projet, j'en laisserais ici une trace.
