### ISSUE TITLE
How to initialize a plugin through a es6?

### ISSUE THREAD

**Issue by 12evgen** [1rosehip/jplist-es6#21]
First of all, I want to express my gratitude for your excellent work, this plugin does not really have competitors in its functionality. I have some questions. 
1. When will it be possible to download this plug-in via npm?
2. And how can I initialize the plugin if I want to connect it as a module ES6?

**Comment by 1rosehip** [comment]
Hi, 
Thank you for the feedback, I'm glad that the plugin is useful for you.
1. I've uploaded the lib to npm, it's accessible here: https://www.npmjs.com/package/jplist-es6
2. There is an ES6 jplist version here: https://github.com/1rosehip/jplist-es6/blob/master/dist/1.2.0/jplist-es6.min.js
Also it's possible to import [index.js](https://github.com/1rosehip/jplist-es6/blob/master/src/1.2.0/index.js) or [jplist.js](https://github.com/1rosehip/jplist-es6/blob/master/src/1.2.0/jplist.js) as entry point in your source files depending on your needs.

**Comment by 12evgen** [comment]
Hi! thanks for the help! I connected the plugin as a module. Is it possible to call Jplist through the constructor (as indicated in the picture)? 

![jplist](https://user-images.githubusercontent.com/25562185/44668051-49580680-aa3e-11e8-89a3-66d232563e75.png)

The following error in the console

![jplist-2](https://user-images.githubusercontent.com/25562185/44668153-70163d00-aa3e-11e8-8f72-ba847b439d16.png)

**Comment by 1rosehip** [comment]
There is some required code that should be added before jplist initialization, you may find it in [index.js](https://github.com/1rosehip/jplist-es6/blob/master/src/1.2.0/index.js). jPList requires **window.jplist.controlTypes** that actually just a ES6 Map of controls that you need in your app. In the index.js file above there is a full list of controls, but you may include only controls that you need.

Also index.js contains **custom events polyfill** for IE 10/11, without it jPList won't work in these browsers.

And the last important thing is binding to jPList APIs:
```js
window.jplist.init = jplist.init.bind(jplist);
window.jplist.refresh = jplist.refresh.bind(jplist);
window.jplist.resetControls = jplist.resetControls.bind(jplist);
window.jplist.resetControl = jplist.resetControl.bind(jplist);
```

**Comment by amrography** [comment]
@12evgen 
try `import "jplist-es6/dist/1.2.0/jplist-es6.min.js";`
