### ISSUE TITLE
BUG: data-path only working with letters in class name

### ISSUE THREAD

**Issue by t40** [1rosehip/jplist-es6#23]
I would like to filter class names like class="51-60" or class="70+" but it seems the filters are only working with letters in class names, so things like data-path=".51-60" is not working.

**Comment by 1rosehip** [comment]
The filters work with JS selectors as defined in spec [here](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector).

**Comment by t40** [comment]
Found a solution. If the class name starts with a letter instead of a number it's working. ;-)

**Comment by 1rosehip** [comment]
I'm glad it's working for you :)
