### ISSUE TITLE
Counter Control

### ISSUE THREAD

**Issue by shane147** [1rosehip/jplist-es6#25]
Would it be possible to enhance JPList to hide data controls, by the data name, where the counter control = 0 on either of the two data modes?

I have several examples where this would be extremely useful in narrowing down the available controls/filters to be more meaningful and logical for the end users.

For example:   

Upon selecting a Cruise Line from a list, the Cruise Ship control would only display the relating 5 ships instead of a list of 500 ships with (0) next to them.

Upon selecting a Destination, only the available Ports of Call would display. 

There are instances where (0) is more appropriate, therefore this would have to be an optional data attribute? 

Many thanks and keep up the good work.

**Comment by 1rosehip** [comment]
There is no builtin way to do this, but you may use **jplist.state** event to perform your custom code when counter control is 0. For example:

```
	counterControlElement.addEventListener('jplist.state', (e) => {

           if(e.jplistState.filtered.length === 0){
		//DO SOME LOGIC	
	   }

        }, false);
```

**Comment by shane147** [comment]
Unfortunately this is beyond my level of knowledge.  Happy to pay to you or anyone else that would like to assist for this feature.  It would make great built in logic and really improve the user search experience

**Comment by shane147** [comment]
Hi,
I went to implement the counter control tonight and whilst everything else works with the HTML structure created by the CMS I'm using, I can't get the text data filter type to work in conjunction with a check box text control.

Are you able to take a look at this CodePen?

https://codepen.io/Shane147/pen/eLyNxq

Many thanks

**Comment by 1rosehip** [comment]
Please check the following working demo:
https://codepen.io/1rosehip/pen/pOpeqW?editors=1010

Counter controls should have different **data-name** attributes because they use different filter properties.

**Comment by shane147** [comment]
Thanks ... I didn’t spot that.

**Comment by 1rosehip** [comment]
You are welcome.
