### ISSUE TITLE
Ajax & Server side 

### ISSUE THREAD

**Issue by sbenfares** [1rosehip/jplist-es6#28]
Hi,

I would like to use your plugin, but my data comes from server-side.

How can i call an ajax (or else) function to populate my data with your plugin ?

Thanks

**Comment by 1rosehip** [comment]
Hi,
Unfortunately ajax is not supported.
Please refer to the following issue:
#18

**Comment by sbenfares** [comment]
OK thanks

**Comment by pflind** [comment]
Could you reconsider adding support for ajax? Probably a lot of the old jPlist users are still looking for this feature in the new version.

**Comment by jiremek** [comment]
I start to work on but have a bug on http.send.
@pflind  Could you help here: #18  ?
