### ISSUE TITLE
Checkbox text filter exact match

### ISSUE THREAD

**Issue by sjahlers** [1rosehip/jplist-es6#31]
Is exact match available for the checkbox text filter? It was requested as an enhancement on the old jplist. For example, I have a list of names and only want to find "Rob." Not Robert, Roberta, Robin, etc.

Thanks!

**Comment by 1rosehip** [comment]
Yes, it's called **data-mode="equal"** - please check the following link:
https://www.jplist.org/documentation/controls/checkbox-text-filter#data-attributes

**Comment by sjahlers** [comment]
Thank you so much! I totally overlooked that. Love the plugin!

**Comment by 1rosehip** [comment]
You are welcome 👍
