### ISSUE TITLE
How to get the the total number of items (not items on first page) after filtering ?

### ISSUE THREAD

**Issue by ghost** [1rosehip/jplist-es6#32]
How is it possible to get the total number of items before/after filtering using multiple filters or change please?
e.jplistState.itemsNumber only returns the items on the first page unfortunately
and this https://www.jplist.org/documentation/controls/counter doesn't do the trick either unfortunately. Is there a way to  globally get the total number of items ?

**Comment by hed101** [comment]
Figured that you used a different source file for your counter examples posted here:
https://www.jplist.org/documentation/controls/counter
Which is: https://codepen.io/1rosehip/pen/zJYbPV.js?v=1

Using your documented source file or any other source file from your examples:
https://www.jplist.org/js/1.2.0/jplist.min.js
THE COUNTER DOESNT WORK.

**Comment by hed101** [comment]
Also, as this is unmaintained, you can't or don't want to support, please take this offline or at least tell possible future users where they're at. Would never have started using it knowing that...

**Comment by hed101** [comment]
Also, as this is unmaintained, you can't or don't want to support, please take this offline or at least tell possible future users where they're at. Would never have started using it knowing that...

**Comment by jiremek** [comment]
Use this: e.jplistState.filtered.length

**Comment by ghost** [comment]
Thanks @jiremek !!!
