### ISSUE TITLE
Case and Space Sensitive Controls & Classes

### ISSUE THREAD

**Issue by shane147** [1rosehip/jplist-es6#8]
Hi,
I'm trying to dynamically populate the values and classes in each of the different controls and filters.

For example, in the case of the check box filter control, the fields enclosed in percentages (%) dynamically populate.  If I need to assign 5 TravelTypes to one item, I have to create 10 database fields. 
5 for each label written in proper case with spaces and then 5 for each class, written in lower case with no spaces.  Even using CSS to convert the case does not overcome the spacing issue.

<label>
    <input
        type="checkbox"
        data-jplist-control="checkbox-path-filter"
        data-path=".%TType1-LowerCase+NoSpaces%"
        data-group="group1"
        data-name="name1"
        checked />
    Filter by %TType1-UpperCase+Spaces-Label%
</label>

<label>
    <input
        type="checkbox"
        data-jplist-control="checkbox-path-filter"
        data-path=".%TType2-LowerCase+NoSpaces%"
        data-group="group1"
        data-name="name1"
        checked />
    Filter by %TType2-UpperCase+Spaces-Label%
</label>

    <div data-jplist-item>
        <div class="%TType1-LowerCase+NoSpaces%">%TType1-UpperCase+Spaces-Label%</div>
        ....
    </div>

    
    <div data-jplist-item>
       <div class="%TType2-LowerCase+NoSpaces%">%TType2-UpperCase+Spaces-Label%</div>
        ....
    </div>

    
    <div data-jplist-item>
        <div class="%TType1-LowerCase+NoSpaces%">%TType1-UpperCase+Spaces-Label%</div>
       <div class="%TType2-LowerCase+NoSpaces%">%TType2-UpperCase+Spaces-Label%</div>
        ....
    </div>

Are you aware a better way of doing this or are there any changes to the script that to avoid this?
i.e. ignoring spaces and case sensitivity would reduce the database fields by 50% and simplify the setup.

Thanks
Shane

**Comment by 1rosehip** [comment]
Please consider using [checkbox text filter control](https://www.jplist.org/documentation/controls/checkbox-text-filter), I've created a [codepen example for it.](https://codepen.io/1rosehip/pen/yqWgoa?editors=1000)
Does it meet the requirements?

Also it has **data-regex** attribute that allows to ignore special characters if needed.

**Comment by shane147** [comment]
With 'Or' logic on this check boxes I think I could make this work.

**Comment by 1rosehip** [comment]
'Or logic' feature is missing for now, I'm going to add it next. The relevant issue is opened [here](https://github.com/1rosehip/jplist-es6/issues/10).

**Comment by shane147** [comment]
OK thanks ... this would help no end in a few areas now you mention it!

**Comment by 1rosehip** [comment]
I've updated the [codepen example](https://codepen.io/1rosehip/pen/MBdOZm) with "OR" logic - please review.
