### ISSUE TITLE
Logic "and" & "or"

### ISSUE THREAD

**Issue by tuktukvlad** [1rosehip/jplist-es6#9]
Hi

Tell me how you can nastify the filtering on the logic "or". Now there is an opportunity to use only "and". In the old version there was such an opportunity. An example in the screenshot.
And I also have a small problem - when there are no results, the pagination buttons remain active.
![filter](https://user-images.githubusercontent.com/22128719/44134028-8bdd67b6-a06b-11e8-8975-9fa1f7cd92ff.png)

Thank you,
Great plug-in

**Comment by tuktukvlad** [comment]
When you change the slider, the product is filtered with bugs
![rangeslider](https://user-images.githubusercontent.com/22128719/44135737-0ae9b832-a073-11e8-9261-03ec2a8f2b0d.gif)

**Comment by 1rosehip** [comment]
Hi, 
Thank you for the feedback.
The "OR" logic is really missing, I added a separate issue for it [here](https://github.com/1rosehip/jplist-es6/issues/10).

I'm trying to reproduce the range slider issue with no luck in the following demo page:
[https://codepen.io/1rosehip/pen/zjLXdb](https://codepen.io/1rosehip/pen/zjLXdb)
What browser do you use?
Could you please send me your HTML structure or update the above codepen?

Thanks

**Comment by 1rosehip** [comment]
Thank you for the demo, I'll check it out and let you know once fixed.

**Comment by tuktukvlad** [comment]
When this option **data-jump="top"** is enabled for pagination, it applies to all controls. Can I enable it only for pagination, and for other elements to disable?

And one more thing, if the rangeslider is put into a collapse menu, and it is hidden by default. The slider is not initialized. In the old version, there was no such problem.
![collapse](https://user-images.githubusercontent.com/22128719/44144272-741386aa-a08f-11e8-8946-663be0662add.PNG)

**Comment by 1rosehip** [comment]
"OR" logic is added through the **data-or="..."** data attributes, you may check the [following codepen](https://codepen.io/1rosehip/pen/MBdOZm) for demo.

**Comment by tuktukvlad** [comment]
Already use, everything works fine! Thanks)

**Comment by shane147** [comment]
Great! ... tested and working as expected here too!

**Comment by 1rosehip** [comment]
You're welcome!

**Comment by 1rosehip** [comment]
I've started checking the [range slider demo](https://codepen.io/tuktukvlad/pen/ajrJza) and I've found out that it filters items by price (**.price**) and sorts it by views (.**views**). Although the HTML update looks strange, it seems that the filtering is working right in any point.

For example, when slider **value 1 =121** and **value 2 = 199** every item price is between [121, 199] and all items are sorted by views.

Am I missing something?

**Comment by tuktukvlad** [comment]
This bug appears when two or more items have the same number of views (.views) and sorted by views.
Then at the moment of changing the slider, a sorting takes place and the items with the same views can be swapped.

I think if add a second sort, for example by name, it can be hidden. That this bug will disappear.
Also, the slider works every second while you pull it. It works on the "slide" event and every time it tries to change the set of elements. If you change the event to "change" and it will apply the filter only when the mouse button is released. This problem must be solved.

Sorry for my awful English, I'm using translation) I hope we understand each other

**Comment by tuktukvlad** [comment]
Checked - with double sorting does not work. In the previous version, if I'm not mistaken, it was possible to use two sorts together

**Comment by 1rosehip** [comment]
It seems that double sorting indeed helps - please check [this](https://codepen.io/1rosehip/pen/jpoZGX?editors=1000).
I should add double sorting stuff to documentation (supporting docs is most difficult part :), and I also like your idea about slider and mouse event, it really makes sense :thumbsup:

**Comment by tuktukvlad** [comment]
Double sorting works fine and really helps. Thanks!
I'm glad that I can help you with something

**Comment by 1rosehip** [comment]
So I'm closing this issue.
2 other things are referenced here:
- [data-jump="top" issue](https://github.com/1rosehip/jplist-es6/issues/11)
- [range slider in a collapsed menu](https://github.com/1rosehip/jplist-es6/issues/12)
